"""Writes lib/cp949_table.dart from Python's cp949 codec.

Usage: python3 tools/gen_cp949.py
"""
import base64
import struct

vals = []
for lead in range(0x81, 0xFF):
    for trail in range(0x41, 0xFF):
        try:
            ch = bytes([lead, trail]).decode("cp949")
            vals.append(ord(ch) if len(ch) == 1 else 0)
        except UnicodeDecodeError:
            vals.append(0)
b = base64.b64encode(struct.pack("<%dH" % len(vals), *vals)).decode()
lines = [b[i:i + 96] for i in range(0, len(b), 96)]
out = [
    "// GENERATED by tools/gen_cp949.py from Python's cp949 codec. Do not edit.",
    "",
    "/// CP949 (Windows Korean, a superset of EUC-KR) double-byte table, base64 of",
    "/// little-endian UTF-16 code units: lead bytes 0x81..0xFE by trail bytes",
    "/// 0x41..0xFE; 0 marks an unassigned pair.",
    "const cp949Table =",
] + ["    '%s'" % l for l in lines]
out[-1] += ";"
with open("lib/cp949_table.dart", "w") as f:
    f.write("\n".join(out) + "\n")
